
package inventory.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InventoryServiceService", targetNamespace = "http://ws.inventory/", wsdlLocation = "http://172.16.254.44:9080/inventory/ws?wsdl")
public class InventoryServiceService
    extends Service
{

    private final static URL INVENTORYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException INVENTORYSERVICESERVICE_EXCEPTION;
    private final static QName INVENTORYSERVICESERVICE_QNAME = new QName("http://ws.inventory/", "InventoryServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.254.44:9080/inventory/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVENTORYSERVICESERVICE_WSDL_LOCATION = url;
        INVENTORYSERVICESERVICE_EXCEPTION = e;
    }

    public InventoryServiceService() {
        super(__getWsdlLocation(), INVENTORYSERVICESERVICE_QNAME);
    }

    public InventoryServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVENTORYSERVICESERVICE_QNAME, features);
    }

    public InventoryServiceService(URL wsdlLocation) {
        super(wsdlLocation, INVENTORYSERVICESERVICE_QNAME);
    }

    public InventoryServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVENTORYSERVICESERVICE_QNAME, features);
    }

    public InventoryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventoryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InventoryService
     */
    @WebEndpoint(name = "InventoryServicePort")
    public InventoryService getInventoryServicePort() {
        return super.getPort(new QName("http://ws.inventory/", "InventoryServicePort"), InventoryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventoryService
     */
    @WebEndpoint(name = "InventoryServicePort")
    public InventoryService getInventoryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.inventory/", "InventoryServicePort"), InventoryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVENTORYSERVICESERVICE_EXCEPTION!= null) {
            throw INVENTORYSERVICESERVICE_EXCEPTION;
        }
        return INVENTORYSERVICESERVICE_WSDL_LOCATION;
    }

}
