
package inventory.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InventoryService", targetNamespace = "http://ws.inventory/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InventoryService {


    /**
     * 
     * @return
     *     returns java.util.List<inventory.ws.Item>
     * @throws DALException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "items", targetNamespace = "http://ws.inventory/", className = "inventory.ws.Items")
    @ResponseWrapper(localName = "itemsResponse", targetNamespace = "http://ws.inventory/", className = "inventory.ws.ItemsResponse")
    public List<Item> items()
        throws DALException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns inventory.ws.Item
     * @throws DALException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateItem", targetNamespace = "http://ws.inventory/", className = "inventory.ws.UpdateItem")
    @ResponseWrapper(localName = "updateItemResponse", targetNamespace = "http://ws.inventory/", className = "inventory.ws.UpdateItemResponse")
    public Item updateItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0)
        throws DALException
    ;

    /**
     * 
     * @param name
     * @return
     *     returns inventory.ws.Item
     * @throws DALException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "itemByName", targetNamespace = "http://ws.inventory/", className = "inventory.ws.ItemByName")
    @ResponseWrapper(localName = "itemByNameResponse", targetNamespace = "http://ws.inventory/", className = "inventory.ws.ItemByNameResponse")
    public Item itemByName(
        @WebParam(name = "name", targetNamespace = "")
        String name)
        throws DALException
    ;

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     * @throws DALException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteItem", targetNamespace = "http://ws.inventory/", className = "inventory.ws.DeleteItem")
    @ResponseWrapper(localName = "deleteItemResponse", targetNamespace = "http://ws.inventory/", className = "inventory.ws.DeleteItemResponse")
    public String deleteItem(
        @WebParam(name = "id", targetNamespace = "")
        long id)
        throws DALException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns inventory.ws.Item
     * @throws DALException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newItem", targetNamespace = "http://ws.inventory/", className = "inventory.ws.NewItem")
    @ResponseWrapper(localName = "newItemResponse", targetNamespace = "http://ws.inventory/", className = "inventory.ws.NewItemResponse")
    public Item newItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0)
        throws DALException
    ;

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.inventory/", className = "inventory.ws.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.inventory/", className = "inventory.ws.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param id
     * @return
     *     returns inventory.ws.Item
     * @throws DALException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "itemById", targetNamespace = "http://ws.inventory/", className = "inventory.ws.ItemById")
    @ResponseWrapper(localName = "itemByIdResponse", targetNamespace = "http://ws.inventory/", className = "inventory.ws.ItemByIdResponse")
    public Item itemById(
        @WebParam(name = "id", targetNamespace = "")
        long id)
        throws DALException
    ;

}
